apiVersion: v1
kind: PersistentVolume
metadata:
  name: team-nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.55.241.196
    path: "/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: team-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi